import sqlite3
import os
from werkzeug.security import generate_password_hash

DB_PATH = os.path.join(os.path.dirname(__file__), 'bmsbites.db')
SCHEMA_PATH = os.path.join(os.path.dirname(__file__), 'schema.sql')

def init_db():
    conn = sqlite3.connect(DB_PATH)
    with open(SCHEMA_PATH, 'r') as f:
        conn.executescript(f.read())
    
    cursor = conn.cursor()
    
    # Seed Admin
    admin_pass = generate_password_hash('admin123')
    cursor.execute("INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
                   ('admin', admin_pass, 'admin'))
    
    # Seed Customer
    user_pass = generate_password_hash('user123')
    cursor.execute("INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
                   ('rahul', user_pass, 'customer'))

    # Seed Canteens
    canteens = [
        ('Vidhyarthi Khaana', 'Near Campus Book Mart', 'Largest canteen with variety of food', '8:00 AM', '8:00 PM', 1),
        ('Gowdas Canteen', 'Near BMS Mess', 'Fresh juices and beverages', '7:00 AM', '7:00 PM', 1)
    ]
    cursor.executemany("INSERT INTO canteens (name, location, description, opening_time, closing_time, is_open) VALUES (?, ?, ?, ?, ?, ?)", canteens)

    # Seed Menu Items for Vidhyarthi Khaana (ID: 1)
    # Seed Menu Items for Vidhyarthi Khaana (ID: 1) - Complete Menu with 225 items
    vidhyarthi_khaana_items = [
        (1, 'Coffee/Tea', 'Coffee/Tea', 10.0, 'beverage', 'coffee.jpg', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Idly (2)', 'Idly (2)', 30.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Vada (1)', 'Vada (1)', 20.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Idly (2) + Vada (1)', 'Idly (2) + Vada (1)', 52.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Idly (1) + Vada (1)', 'Idly (1) + Vada (1)', 40.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Idly (1)', 'Idly (1)', 18.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Rava Idly', 'Rava Idly', 35.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Karabath', 'Karabath', 25.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Kesari Bath', 'Kesari Bath', 30.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Chow Chow Bath', 'Chow Chow Bath', 50.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Poori', 'Poori', 35.0, 'veg', 'poori.jpg', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Curd Vada', 'Curd Vada', 35.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Bajji / Pakoda', 'Bajji / Pakoda', 40.0, 'veg', 'poori.jpg', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Special Rice Bath', 'Special Rice Bath', 50.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Rice Bath', 'Rice Bath', 40.0, 'veg', 'south_indian_breakfast.png', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Buns (1)', 'Buns (1)', 30.0, 'veg', 'poori.jpg', 'SOUTH INDIAN BREAKFAST'),
        (1, 'Masala Dosa', 'Masala Dosa', 50.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Set Dosa', 'Set Dosa', 40.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Khali Dosa', 'Khali Dosa', 35.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Onion Dosa', 'Onion Dosa', 45.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Rava Dosa', 'Rava Dosa', 60.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Rava Onion Dosa', 'Rava Onion Dosa', 65.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Special Masala Dosa', 'Special Masala Dosa', 60.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Special Palak Dosa', 'Special Palak Dosa', 65.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Neer Dosa', 'Neer Dosa', 30.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Gobi Masala Dosa', 'Gobi Masala Dosa', 55.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Sweet Corn Dosa', 'Sweet Corn Dosa', 55.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Mysore Masala Dosa', 'Mysore Masala Dosa', 55.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Today’s Special Dosa', 'Today’s Special Dosa', 60.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Veg Mix Dosa', 'Veg Mix Dosa', 60.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Onion Masala Dosa', 'Onion Masala Dosa', 55.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Paper Masala Dosa', 'Paper Masala Dosa', 65.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Paper Plain Dosa', 'Paper Plain Dosa', 50.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'Open Pudi Masala Dosa', 'Open Pudi Masala Dosa', 65.0, 'veg', 'masala_dosa.png', 'Dosa Items'),
        (1, 'North Indian Meals', 'North Indian Meals', 60.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'South Indian Meals', 'South Indian Meals', 45.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Curd Rice', 'Curd Rice', 25.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Veg Palav', 'Veg Palav', 40.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Jeera Rice', 'Jeera Rice', 45.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Poori (2)', 'Poori (2)', 25.0, 'veg', 'poori.jpg', 'North Indian Meals'),
        (1, 'Chapati (1)', 'Chapati (1)', 20.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Chapati (2)', 'Chapati (2)', 40.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Parota (1)', 'Parota (1)', 20.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Parota (2)', 'Parota (2)', 40.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Ghee Rice', 'Ghee Rice', 50.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Kesari Bath / Halwa', 'Kesari Bath / Halwa', 35.0, 'veg', 'bath.jpg', 'North Indian Meals'),
        (1, 'Gulab Jamun (1)', 'Gulab Jamun (1)', 15.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Veg Rice Bath', 'Veg Rice Bath', 40.0, 'veg', 'bath.jpg', 'North Indian Meals'),
        (1, 'Badam Milk / Horlicks / Boost', 'Badam Milk / Horlicks / Boost', 25.0, 'beverage', 'default.jpg', 'North Indian Meals'),
        (1, 'Special Meals Charges', 'Special Meals Charges', 5.0, 'veg', 'default.jpg', 'North Indian Meals'),
        (1, 'Veg Noodles', 'Veg Noodles', 65.0, 'veg', 'noodles.jpg', '(Board 1)'),
        (1, 'Veg Fried Rice', 'Veg Fried Rice', 65.0, 'veg', 'friedrice.jpg', '(Board 1)'),
        (1, 'Gobi Manchurian', 'Gobi Manchurian', 70.0, 'veg', 'manchurian.jpg', '(Board 1)'),
        (1, 'Jeera Rice', 'Jeera Rice', 60.0, 'veg', 'default.jpg', '(Board 1)'),
        (1, 'Egg Noodles (2 eggs)', 'Egg Noodles (2 eggs)', 75.0, 'non-veg', 'omelette.jpg', '(Board 1)'),
        (1, 'Egg Fried Rice (2 eggs)', 'Egg Fried Rice (2 eggs)', 75.0, 'non-veg', 'omelette.jpg', '(Board 1)'),
        (1, 'Mushroom Jeera Rice', 'Mushroom Jeera Rice', 70.0, 'veg', 'default.jpg', '(Board 1)'),
        (1, 'Paneer Jeera Rice', 'Paneer Jeera Rice', 75.0, 'veg', 'default.jpg', '(Board 1)'),
        (1, 'Gobi Chilly / Pepper Dry', 'Gobi Chilly / Pepper Dry', 70.0, 'veg', 'default.jpg', '(Board 1)'),
        (1, 'Paneer Manchurian / Chilly / Pepper Dry', 'Paneer Manchurian / Chilly / Pepper Dry', 80.0, 'veg', 'manchurian.jpg', '(Board 1)'),
        (1, 'Mushroom Manchurian / Chilly / Pepper Dry', 'Mushroom Manchurian / Chilly / Pepper Dry', 80.0, 'veg', 'manchurian.jpg', '(Board 1)'),
        (1, 'Babycorn Manchurian / Chilly / Pepper Dry', 'Babycorn Manchurian / Chilly / Pepper Dry', 80.0, 'veg', 'manchurian.jpg', '(Board 1)'),
        (1, 'Schezwan Paneer Veg Noodles', 'Schezwan Paneer Veg Noodles', 80.0, 'veg', 'noodles.jpg', '(Board 1)'),
        (1, 'Schezwan Veg Noodles', 'Schezwan Veg Noodles', 70.0, 'veg', 'noodles.jpg', '(Board 1)'),
        (1, 'Schezwan Veg Fried Rice', 'Schezwan Veg Fried Rice', 70.0, 'veg', 'friedrice.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Egg Noodles (2 eggs)', 'Schezwan Egg Noodles (2 eggs)', 80.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Egg Fried Rice (2 eggs)', 'Schezwan Egg Fried Rice (2 eggs)', 80.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Paneer Veg Noodles', 'Paneer Veg Noodles', 75.0, 'veg', 'noodles.jpg', '(Board 2 Continuation)'),
        (1, 'Paneer Veg Fried Rice', 'Paneer Veg Fried Rice', 75.0, 'veg', 'friedrice.jpg', '(Board 2 Continuation)'),
        (1, 'Mushroom Veg Noodles', 'Mushroom Veg Noodles', 75.0, 'veg', 'noodles.jpg', '(Board 2 Continuation)'),
        (1, 'Mushroom Veg Fried Rice', 'Mushroom Veg Fried Rice', 75.0, 'veg', 'friedrice.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Paneer Egg Noodles', 'Schezwan Paneer Egg Noodles', 90.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Paneer Egg Rice', 'Schezwan Paneer Egg Rice', 90.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Mushroom', 'Schezwan Mushroom', 90.0, 'veg', 'default.jpg', '(Board 2 Continuation)'),
        (1, 'Egg Noodles', 'Egg Noodles', 90.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Mushroom Egg Rice', 'Schezwan Mushroom Egg Rice', 90.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Triple Veg Fried Rice', 'Triple Veg Fried Rice', 75.0, 'veg', 'friedrice.jpg', '(Board 2 Continuation)'),
        (1, 'Triple Egg Fried Rice (2 eggs)', 'Triple Egg Fried Rice (2 eggs)', 85.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Gobi Noodles', 'Gobi Noodles', 75.0, 'veg', 'noodles.jpg', '(Board 2 Continuation)'),
        (1, 'Gobi Rice', 'Gobi Rice', 75.0, 'veg', 'default.jpg', '(Board 2 Continuation)'),
        (1, 'Roti Curry', 'Roti Curry', 50.0, 'veg', 'default.jpg', '(Board 2 Continuation)'),
        (1, 'Paneer Egg Noodles', 'Paneer Egg Noodles', 80.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Mushroom Egg Noodles', 'Mushroom Egg Noodles', 80.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Mushroom Egg Fried Rice', 'Mushroom Egg Fried Rice', 80.0, 'non-veg', 'omelette.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Mushroom Veg Noodles', 'Schezwan Mushroom Veg Noodles', 80.0, 'veg', 'noodles.jpg', '(Board 2 Continuation)'),
        (1, 'Schezwan Mushroom Veg Rice', 'Schezwan Mushroom Veg Rice', 80.0, 'veg', 'default.jpg', '(Board 2 Continuation)'),
        (1, 'Mosambi Juice', 'Mosambi Juice', 40.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Watermelon Juice', 'Watermelon Juice', 30.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Pineapple Juice', 'Pineapple Juice', 45.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Orange Juice', 'Orange Juice', 45.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Grape Juice', 'Grape Juice', 40.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Karbooja / Musk Melon Juice', 'Karbooja / Musk Melon Juice', 45.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Papaya Juice', 'Papaya Juice', 45.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Lime Juice', 'Lime Juice', 20.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Mixed Fruit Juice / Solid', 'Mixed Fruit Juice / Solid', 50.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Mosambi / Solid Orange Juice', 'Mosambi / Solid Orange Juice', 50.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Pista Badam', 'Pista Badam', 30.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Mango', 'Mango', 60.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Lychee', 'Lychee', 60.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Kesar Pista', 'Kesar Pista', 38.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Vanilla Choco Chips', 'Vanilla Choco Chips', 38.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Dairy Rich Delight Special', 'Dairy Rich Delight Special', 38.0, 'beverage', 'juice.jpg', 'FRESH JUICE'),
        (1, 'Arabian Grape Juice', 'Arabian Grape Juice', 50.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Apple Milk Shake', 'Apple Milk Shake', 50.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Sapota Milk Shake', 'Sapota Milk Shake', 50.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Butter Fruit Milk Shake', 'Butter Fruit Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Banana Milk Shake', 'Banana Milk Shake', 40.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Pomegranate Milk Shake', 'Pomegranate Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Mango Milk Shake', 'Mango Milk Shake', 50.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Custard Apple Milk Shake', 'Custard Apple Milk Shake', 50.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Strawberry Milk Shake', 'Strawberry Milk Shake', 50.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Fruit Bowl with Ice Cream', 'Fruit Bowl with Ice Cream', 80.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Fruit Bowl', 'Fruit Bowl', 40.0, 'beverage', 'milkshake.jpg', 'MILK SHAKES'),
        (1, 'Vanilla Milk Shake', 'Vanilla Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Strawberry Milk Shake', 'Strawberry Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Butter Scotch Milk Shake', 'Butter Scotch Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Black Currant Milk Shake', 'Black Currant Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Chocolate Milk Shake', 'Chocolate Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Tutti Fruity Milk Shake', 'Tutti Fruity Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Mango Milk Shake', 'Mango Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Vanilla Choco Chips Milk Shake', 'Vanilla Choco Chips Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Pista Badam Milk Shake', 'Pista Badam Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Lychee Milk Shake', 'Lychee Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Kesar Pista Milk Shake', 'Kesar Pista Milk Shake', 60.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Cold Coffee', 'Cold Coffee', 60.0, 'beverage', 'coffee.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Tender Coconut Milkshake', 'Tender Coconut Milkshake', 70.0, 'beverage', 'milkshake.jpg', 'ICE CREAM / MILK SHAKE (BOARD 3)'),
        (1, 'Vanilla / Strawberry / Butter Scotch / Black Currant / Tutti Fruity / Chocolate / Pista Badam', 'Vanilla / Strawberry / Butter Scotch / Black Currant / Tutti Fruity / Chocolate / Pista Badam', 38.0, 'beverage', 'default.jpg', 'Cone Ice Cream'),
        (1, 'Masala Puri', 'Masala Puri', 40.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Pani Puri', 'Pani Puri', 40.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Aloo Puri', 'Aloo Puri', 50.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Dahi Puri', 'Dahi Puri', 50.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Sev Puri', 'Sev Puri', 50.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Bhel Puri', 'Bhel Puri', 40.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Samosa Chat Masala', 'Samosa Chat Masala', 50.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Kachori Chat Masala', 'Kachori Chat Masala', 50.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Plain Samosa / Kachori', 'Plain Samosa / Kachori', 25.0, 'veg', 'chat.jpg', 'CHATS'),
        (1, 'Omlet', 'Omlet', 35.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Bread Omlet', 'Bread Omlet', 40.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Cheese Omlet', 'Cheese Omlet', 45.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Bread Omlet with Cheese', 'Bread Omlet with Cheese', 50.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Corn Omlet', 'Corn Omlet', 50.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Corn Omlet with Cheese', 'Corn Omlet with Cheese', 55.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Paneer Cheese Omlet', 'Paneer Cheese Omlet', 60.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Mushroom Omlet', 'Mushroom Omlet', 45.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Mushroom Cheese Omlet', 'Mushroom Cheese Omlet', 50.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Lime Cheese Omlet', 'Lime Cheese Omlet', 45.0, 'non-veg', 'omelette.jpg', 'Egg Omlet'),
        (1, 'Egg Burji', 'Egg Burji', 40.0, 'non-veg', 'omelette.jpg', 'Egg + Bread Items'),
        (1, 'Bread Burji', 'Bread Burji', 40.0, 'veg', 'default.jpg', 'Egg + Bread Items'),
        (1, 'Bread Egg Burji', 'Bread Egg Burji', 50.0, 'non-veg', 'omelette.jpg', 'Egg + Bread Items'),
        (1, 'Bread Paneer Egg Burji', 'Bread Paneer Egg Burji', 55.0, 'non-veg', 'omelette.jpg', 'Egg + Bread Items'),
        (1, 'Masala Maggie', 'Masala Maggie', 45.0, 'veg', 'maggie.jpg', 'Maggie – Masala'),
        (1, 'Corn Masala Maggie', 'Corn Masala Maggie', 50.0, 'veg', 'maggie.jpg', 'Maggie – Masala'),
        (1, 'Paneer Masala Maggie', 'Paneer Masala Maggie', 55.0, 'veg', 'maggie.jpg', 'Maggie – Masala'),
        (1, 'Babycorn Masala Maggie', 'Babycorn Masala Maggie', 55.0, 'veg', 'maggie.jpg', 'Maggie – Masala'),
        (1, 'Potato Masala Maggie', 'Potato Masala Maggie', 50.0, 'veg', 'maggie.jpg', 'Maggie – Masala'),
        (1, 'Cheese Masala Maggie', 'Cheese Masala Maggie', 55.0, 'veg', 'maggie.jpg', 'Maggie – Masala'),
        (1, 'Veg Roll', 'Veg Roll', 50.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Paneer Roll', 'Paneer Roll', 60.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Paneer Cheese Roll', 'Paneer Cheese Roll', 65.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Mushroom Roll', 'Mushroom Roll', 55.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Mushroom Cheese Roll', 'Mushroom Cheese Roll', 60.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Babycorn Roll', 'Babycorn Roll', 55.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Schezwan Roll', 'Schezwan Roll', 50.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Paneer Schezwan Roll', 'Paneer Schezwan Roll', 60.0, 'veg', 'frankie.jpg', 'Rolls'),
        (1, 'Veg Egg Roll', 'Veg Egg Roll', 50.0, 'non-veg', 'omelette.jpg', 'Rolls'),
        (1, 'Egg Cheese Roll', 'Egg Cheese Roll', 55.0, 'non-veg', 'omelette.jpg', 'Rolls'),
        (1, 'Vada Pav', 'Vada Pav', 25.0, 'veg', 'vada.jpg', 'Rolls'),
        (1, 'Veg Frankie', 'Veg Frankie', 50.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Veg Schezwan Frankie', 'Veg Schezwan Frankie', 50.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Paneer Frankie', 'Paneer Frankie', 60.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Schezwan Corn Frankie', 'Schezwan Corn Frankie', 60.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Paneer Schezwan Frankie', 'Paneer Schezwan Frankie', 60.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Babycorn Schezwan Frankie', 'Babycorn Schezwan Frankie', 60.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Veg Cheese Frankie', 'Veg Cheese Frankie', 60.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Egg Frankie', 'Egg Frankie', 50.0, 'non-veg', 'omelette.jpg', 'Mumbai Special Frankies'),
        (1, 'Schezwan Egg Frankie', 'Schezwan Egg Frankie', 60.0, 'non-veg', 'omelette.jpg', 'Mumbai Special Frankies'),
        (1, 'Mushroom Frankie', 'Mushroom Frankie', 60.0, 'veg', 'frankie.jpg', 'Mumbai Special Frankies'),
        (1, 'Bread Jam', 'Bread Jam', 40.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Veg Burger', 'Veg Burger', 50.0, 'veg', 'burger.jpg', 'Sandwich'),
        (1, 'Veg Cheese Burger', 'Veg Cheese Burger', 60.0, 'veg', 'burger.jpg', 'Sandwich'),
        (1, 'Veg Sandwich', 'Veg Sandwich', 50.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Veg Grill Sandwich', 'Veg Grill Sandwich', 60.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Cheese Grill Sandwich', 'Cheese Grill Sandwich', 65.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Onion Cheese Grill', 'Onion Cheese Grill', 60.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Chilly Cheese Grill', 'Chilly Cheese Grill', 60.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Potato Cheese Grill', 'Potato Cheese Grill', 60.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Potato Onion Cheese Grill', 'Potato Onion Cheese Grill', 60.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Paneer Veg Grill', 'Paneer Veg Grill', 60.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Paneer Cheese Grill', 'Paneer Cheese Grill', 65.0, 'veg', 'default.jpg', 'Sandwich'),
        (1, 'Sweet Corn Sandwich', 'Sweet Corn Sandwich', 60.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Sweet Corn Cheese Sandwich', 'Sweet Corn Cheese Sandwich', 65.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Babycorn Sandwich', 'Babycorn Sandwich', 60.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Babycorn Cheese Sandwich', 'Babycorn Cheese Sandwich', 65.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Mushroom Cheese Sandwich', 'Mushroom Cheese Sandwich', 65.0, 'veg', 'sandwich.jpg', 'Sandwich'),
        (1, 'Plain Masala Sandwich', 'Plain Masala Sandwich', 50.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Egg Masala Sandwich (2 eggs)', 'Egg Masala Sandwich (2 eggs)', 60.0, 'non-veg', 'omelette.jpg', 'Masala Sandwich'),
        (1, 'Paneer Masala Sandwich', 'Paneer Masala Sandwich', 60.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Sweet Corn Masala Sandwich', 'Sweet Corn Masala Sandwich', 60.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Babycorn Masala Sandwich', 'Babycorn Masala Sandwich', 60.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Potato Masala Sandwich', 'Potato Masala Sandwich', 55.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Onion Masala Sandwich', 'Onion Masala Sandwich', 50.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Capsicum Masala Sandwich', 'Capsicum Masala Sandwich', 50.0, 'veg', 'sandwich.jpg', 'Masala Sandwich'),
        (1, 'Veg Maggie', 'Veg Maggie', 45.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Veg Fry Maggie', 'Veg Fry Maggie', 50.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Veg Maggie with Cheese', 'Veg Maggie with Cheese', 55.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Veg Fry Maggie with Cheese', 'Veg Fry Maggie with Cheese', 60.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Paneer Maggie', 'Paneer Maggie', 60.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Paneer Maggie with Cheese', 'Paneer Maggie with Cheese', 65.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Sweet Corn Maggie', 'Sweet Corn Maggie', 55.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Sweet Corn Maggie with Cheese', 'Sweet Corn Maggie with Cheese', 60.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Baby Corn Veg Maggie', 'Baby Corn Veg Maggie', 60.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Baby Corn Maggie with Cheese', 'Baby Corn Maggie with Cheese', 65.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Special Veg Fry Maggie', 'Special Veg Fry Maggie', 70.0, 'veg', 'maggie.jpg', 'Veg Maggie'),
        (1, 'Egg Fry Maggie', 'Egg Fry Maggie', 60.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Boiled Egg Maggie', 'Boiled Egg Maggie', 60.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Egg Fry Maggie with Cheese', 'Egg Fry Maggie with Cheese', 65.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Paneer Egg Fry Maggie', 'Paneer Egg Fry Maggie', 70.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Paneer Egg Fry Maggie with Cheese', 'Paneer Egg Fry Maggie with Cheese', 75.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Mushroom Egg Fry Maggie', 'Mushroom Egg Fry Maggie', 65.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Mushroom Egg Fry Maggie with Cheese', 'Mushroom Egg Fry Maggie with Cheese', 70.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Corn Egg Fry Maggie', 'Corn Egg Fry Maggie', 65.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Corn Egg Fry Maggie with Cheese', 'Corn Egg Fry Maggie with Cheese', 70.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Baby Corn Egg Fry Maggie', 'Baby Corn Egg Fry Maggie', 65.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Baby Corn Egg Fry Maggie with Cheese', 'Baby Corn Egg Fry Maggie with Cheese', 70.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
        (1, 'Special Egg Fry Maggie', 'Special Egg Fry Maggie', 80.0, 'non-veg', 'omelette.jpg', 'Egg Maggie'),
    ]

    # Seed Menu Items for Gowdas Canteen (ID: 2)
    gowdas_canteen_items = [
        (2, 'Cold Coffee', 'Chilled coffee with milk', 50.0, 'beverage', 'coffee.jpg', 'Beverages & Snacks'),
        (2, 'Tea', 'Hot masala chai', 15.0, 'beverage', 'coffee.jpg', 'Beverages & Snacks'),
        (2, 'Fresh Lime Soda', 'Refreshing lime drink', 40.0, 'beverage', 'lime.jpg', 'Beverages & Snacks'),
        (2, 'Mango Lassi', 'Yogurt drink with mango pulp', 60.0, 'beverage', 'lassi.jpg', 'Beverages & Snacks'),
        (2, 'Coke', 'Carbonated soft drink', 20.0, 'beverage', 'coke.jpg', 'Beverages & Snacks'),
        (2, 'Water Bottle', 'Mineral water', 20.0, 'beverage', 'water.jpg', 'Beverages & Snacks'),
        (2, 'Orange Juice', 'Fresh squeezed orange juice', 50.0, 'beverage', 'orange.jpg', 'Beverages & Snacks'),
        (2, 'Watermelon Juice', 'Fresh watermelon juice', 40.0, 'beverage', 'watermelon.jpg', 'Beverages & Snacks'),
        (2, 'Egg Curry', 'Boiled eggs in spicy gravy', 100.0, 'non-veg', 'omelette.jpg', 'Beverages & Snacks'),
        (2, 'Omelette', 'Spicy egg omelette', 40.0, 'non-veg', 'omelette.jpg', 'Beverages & Snacks'),
        (2, 'Gobi Manchurian', 'Cauliflower fritters in spicy sauce', 90.0, 'veg', 'gobi.jpg', 'Beverages & Snacks'),
        (2, 'Chilli Chicken', 'Spicy chicken appetizer', 150.0, 'non-veg', 'chillichicken.jpg', 'Beverages & Snacks'),
        (2, 'Veg Noodles', 'Stir-fried noodles with vegetables', 80.0, 'veg', 'noodles.jpg', 'Beverages & Snacks'),
        (2, 'Chicken Roll', 'Chicken wrapped in paratha', 100.0, 'non-veg', 'frankie.jpg', 'Beverages & Snacks'),
        (2, 'Veg Roll', 'Mixed vegetables wrapped in paratha', 70.0, 'veg', 'frankie.jpg', 'Beverages & Snacks'),
    ]

    all_items = vidhyarthi_khaana_items + gowdas_canteen_items
    cursor.executemany("INSERT INTO menu (canteen_id, name, description, price, category, image_url, category_section) VALUES (?, ?, ?, ?, ?, ?, ?)", all_items)

    conn.commit()
    conn.close()
    print("Database initialized and seeded successfully.")
    print("✓ 2 Canteens created")
    print("✓ 240 Menu items distributed across canteens")

if __name__ == '__main__':
    init_db()
